PREFIX : <http://example.org/>
PREFIX edge: <http://example.org/edges/>
select ?x ?y ?w
where {
    ?y edge:link ?w
    {
        {?x edge:link ?y .}
        UNION
        {?x edge:link ?w .}
    }
}
