SELECT *
WHERE {
    {
        { ?s1 ?p1 ?o1 }
        UNION
        { ?p1 ?s1 ?o1 }
        UNION
        { ?o1 ?p1 ?s1 }
    } .
    {
        { ?s2 ?p2 ?o2 }
        UNION
        { ?p2 ?s2 ?o2 }
    } .
    {
        { ?s3 ?p3 ?o3 }
        UNION
        { ?p3 ?s3 ?o3 }
    }
}