PREFIX : <http://example.org/we_are/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?h (AVG(?v) as ?v)
WHERE {
    ?p :hasRating ?r .
    ?r :hospital_id ?h .
    ?r :rating ?v .
}
GROUP BY ?h