PREFIX : <http://example.org/we_are/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?rating ?hospital
WHERE {
    ?pod :hospital_id ?hospital .
    ?pod :rating ?rating .
    ?pod :date ?givendate .
    FILTER (?givendate < "2026-01-31"^^xsd:date)
    FILTER (?rating < 5)
}