PREFIX : <http://example.org/>
PREFIX edge: <http://example.org/edges/>
select ?x ?z
where {
    ?x edge:link ?y .
    {
        SELECT ?y
        WHERE {
            ?y edge:link ?z .
        }
    }
}
