PREFIX : <http://example.org/>
PREFIX edge: <http://example.org/edges/>
select ?x ?y1 ?y2 ?y3 ?y4
where {
    ?x edge:link ?y1 .
    ?x edge:link ?y2 .
    ?x edge:link ?y3 .
    ?x edge:link ?y4 .
}
